---
apiVersion: v1
kind: Service
metadata:
  name: podlink
  namespace: default
spec:
  clusterIP: None
  selector:
    app: podlink
  ports:
  - name: grpclb
    port: 443
    targetPort: 443
    protocol: TCP
